#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("christmascalc.Resource", IsApplication=true)]

namespace christmascalc
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int Calculator_Current_Number_text = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int Calculator_Full_equation = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int Scroll1 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int Scroll2 = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int TheGrid = 2131099648;
			
			// aapt resource value: 0x7f060017
			public const int button0 = 2131099671;
			
			// aapt resource value: 0x7f060012
			public const int button1 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int button2 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int button3 = 2131099668;
			
			// aapt resource value: 0x7f06000e
			public const int button4 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int button5 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int button6 = 2131099664;
			
			// aapt resource value: 0x7f06000a
			public const int button7 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int button8 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int button9 = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int buttonBackArrow = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int buttonCE = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int buttonChristmas = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int buttonClear = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int buttonDivide = 2131099657;
			
			// aapt resource value: 0x7f060018
			public const int buttonDot = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int buttonEquals = 2131099673;
			
			// aapt resource value: 0x7f060011
			public const int buttonMinus = 2131099665;
			
			// aapt resource value: 0x7f060015
			public const int buttonPluse = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int buttonPluseorMinus = 2131099670;
			
			// aapt resource value: 0x7f06000d
			public const int buttonTimes = 2131099661;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int ChristmasCalcMusic = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
